version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn ng build --prod
      
      - run:
          command: |
            docker build -t sicotine.azurecr.io/hello:1.0 .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS sicotine.azurecr.io
      - run:
          command: |
            docker push sicotine.azurecr.io/hello:1.0
